services:
  api:
    container_name: hhplus-nestjs
    image: nestjs-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      # ✨ Target the dev stage
      target: dev
    # Mount host directory to docker container to support watch mode
    volumes:
      - .:/app
      # This ensures that the NestJS container manages the node_modules folder
      # rather than synchronizes it with the host machine
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - hhplus-net
    command: pnpm run start
  # If you need DB, assign here
networks:
  hhplus-net:
